const StaticWish = {
    'trend': [
        {"id":1,"date":"2021-07-23T06:22:18.207Z","title":"Festive Offer","subtitle":"Biggest Price Drop For Mobile","description":"Biggest Price Drop For Mobile in Amazon Great Indian Festivel","type":"phone","link":"https://amzn.to/2WypY57","image":null},
        {"id":3,"date":"2021-07-26T10:11:29.866Z","title":"Festive Deal","subtitle":"Apple Watch on Huge Discount","description":"New Apple Watch SE (GPS, 44mm) - Space Grey Aluminium Case with Black Sport Band","type":"watch","link":"https://amzn.to/39WgEuW","image":null},
        {"id":2,"date":"2021-07-23T08:57:59.148Z","title":"Festive Offer","subtitle":"Best TWS Earphone Within 4000","description":"JBL C115 TWS by Harman, True Wireless Earbuds with Mic, Jumbo 21 Hours Playtime with Quick Charge, True Bass","type":"earphones","link":"https://amzn.to/3mhCY7X","image":null},
        {"id":6,"date":"2021-07-28T08:50:12.566Z","title":"Festive Deal","subtitle":"Best 55-inch TV to Buy In Amazon Sale","description":"Redmi 139 cm (55 inches) 4K Ultra HD Android Smart LED TV X55|L55M6-RA (Black) (2021 Model)","type":"television","link":"https://amzn.to/2YiWhWv","image":null},
        {"id":5,"date":"2021-07-27T10:17:36.670Z","title":"Festive Deal","subtitle":"Best Laptop To Buy In Flipkart Big Billion Day Sale","description":"HP Pavilion Core i5 11th Gen - (16 GB/512 GB SSD/Windows 10 Home/2 GB Graphics)","type":"laptop","link":"https://www.flipkart.com/hp-pavilion-core-i5-11th-gen-16-gb-512-gb-ssd-windows-10-home-14-dv0054tu-thin-light-laptop/p/itm36b7d040b7f87?pid=COMGY8RDNJX8FWGH&lid=LSTCOMGY8RDNJX8FWGHNMQSO2&marketplace=FLIPKART&q=HP+Pavilion+Core+i5+11th+Gen&store=6bo","image":null},
        {"id":4,"date":"2021-07-27T01:44:25.849Z","title":"Festive Deal","subtitle":"Best selling DSLR Camera","description":"Canon EOS 1500D DSLR Camera Body+ 18-55 mm IS II Lens  (Black)","type":"camera","link":"https://www.flipkart.com/canon-eos-1500d-dslr-camera-body-18-55-mm-ii-lens/p/itm033175ceb4ddd?pid=DLLFAEWE22ZAERXG&lid=LSTDLLFAEWE22ZAERXGWBJCOR&marketplace=FLIPKART&store=jek%2Fp31%2Ftrv&srno=b_1_1&otracker=dynamic_omu_infinite_Top%2BDeals%2BOn%2BElectronics%2B_3_1.dealCard.OMU_INFINITE_39XURRK6N6EX&fm=neo%2Fmerchandising&iid=7cc0fadd-9a3a-45fc-be82-d22196001855.DLLFAEWE22ZAERXG.SEARCH&ppt=dynamic&ppn=dynamic&ssid=y2q791ahqo0000001633195387176","image":null},
    ],
    'bestDeal': [
        {
            "id": "db_010",
            "title": "other",
            "custom_title": "Alexa Echo Show 5",
            "result": {
              "id": "bdr_010",
              "product_name": "Echo Show 5",
              "product_type": "other",
              "product_brand": "Amazon",
              "product_link": "https://amzn.to/3PyLWLB",
              "product_price": 3999,
              "product_thumbnail": "https://m.media-amazon.com/images/I/61DInKN4VoL._SL252_.jpg",
              "closing_remark": "Smart Speaker with Alexa | Hands Free Music Control",
            }
        },
        {
            "id": "db_009",
            "title": "phone",
            "custom_title": "iPhone 13 price drop",
            "result": {
              "id": "bdr_009",
              "product_name": "Apple iPhone 13",
              "product_type": "phone",
              "product_brand": "apple",
              "product_link": "https://amzn.to/3b5xz27",
              "product_price": 68900,
              "product_thumbnail": "https://m.media-amazon.com/images/I/61-r9zOKBCL._SL252_.jpg",
              "closing_remark": "Great Battery Performance | Amazin Camera | Picture Quality | Video Recording",
            }
        },
        {
            "id": "db_004",
            "title": "laptop",
            "custom_title": "Light But Powerful Laptop",
            "custom_cta" : "View now",
            "result": {
              "id": "bdr_004",
              "product_name": "LG Gram17",
              "product_type": "laptop",
              "product_brand": "LG",
              "product_link": "https://amzn.to/3BadJxu",
              "product_price": 110000,
              "product_thumbnail": "https://m.media-amazon.com/images/I/51r17oSYqZL._SL252_.jpg",
              "closing_remark": "12th Gen Core i7 | 16 GB Ram | 512 GB SSD | 17 inch screen",
            }
          },
        {
            "id": "db_007",
            "title": "laptop",
            "custom_title": "Budget Laptop",
            "result": {
              "id": "bdr_007",
              "product_name": "HP 15s",
              "product_type": "laptop",
              "product_brand": "HP",
              "product_link": "https://amzn.to/3b5xLOT",
              "product_price": 37900,
              "product_thumbnail": "https://m.media-amazon.com/images/I/81PbxeJomjL._SL252_.jpg",
              "closing_remark": "11th Gen i3 | 512 GB SSD | 15.6 Inch Screen",
            }
        },
        {
            "id": "db_006",
            "title": "other",
            "custom_title": "Read with Style",
            "result": {
              "id": "bdr_006",
              "product_name": "Kindle 10th Gen",
              "product_type": "other",
              "product_brand": "Amazon",
              "product_link": "https://amzn.to/3cyrnjI",
              "product_price": 6499,
              "product_thumbnail": "https://m.media-amazon.com/images/I/61xtpHL4xyL._SL252_.jpg",
              "closing_remark": "6 Inch Screen | Built in light",
            }
          },
          {
            "id": "db_008",
            "title": "watch",
            "custom_title": "Track your health",
            "result": {
              "id": "bdr_008",
              "product_name": "https://amzn.to/3ODUobe",
              "product_type": "watch",
              "product_brand": "Amazefit",
              "product_link": "https://amzn.to/3ODUobe",
              "product_price": 4999,
              "product_thumbnail": "https://m.media-amazon.com/images/I/51W+7ZMog7L._SL252_.jpg",
              "closing_remark": "14 days battery | Sleep and Stress Monitoring | SpO2",
            }
          },
        // {
        //     "id": "db_001",
        //     "title": "earphones",
        //     "custom_title": "Half Price for Redmi Earbuds 2",
        //     "custom_cta" : "View now",
        //     "result": {
        //       "id": "bdr_001",
        //       "product_name": "Redmi Earbuds 2C",
        //       "product_type": "earphones",
        //       "product_brand": "redmi",
        //       "product_link": "https://amzn.to/3BxopCK",
        //       "product_price": 849,
        //       "product_thumbnail": "https://m.media-amazon.com/images/I/61tNLS9q4gL._SL252_.jpg",
        //       "closing_remark": "124Hrs Playback| Bluetooth 5.0 Wireless Headphones with Deep Bass | IPX4 Water Resistance, Ergonomic & Snug-fit, Voice Assistance,",
        //     }
        //   },
        //   {
        //     "id": "db_002",
        //     "title": "others",
        //     "custom_title": "Microwave Oven for large family",
        //     "custom_cta" : "View now",
        //     "result": {
        //       "id": "bdr_002",
        //       "product_name": "Samsung 28 L Convection Microwave Oven",
        //       "product_type": "others",
        //       "product_brand": "Samsung",
        //       "product_link": "https://amzn.to/3EsVku0",
        //       "product_price": 11590,
        //       "product_thumbnail": "https://m.media-amazon.com/images/I/81wx0ua+yCL._SL252_.jpg",
        //       "closing_remark": "Suitable for large families | 1 year wrranty | Child Lock Enabled",
        //     }
        //   },
        //   {
        //     "id": "db_003",
        //     "title": "phone",
        //     "custom_title": "Bank offer of 10% on OPPO A33",
        //     "custom_cta" : "View now",
        //     "result": {
        //       "id": "bdr_003",
        //       "product_name": "OPPO A33",
        //       "product_type": "phone",
        //       "product_brand": "OPPO",
        //       "product_link": "https://www.flipkart.com/oppo-a33-moonlight-black-32-gb/p/itmec568a00f8945?pid=MOBFWQBWVGZYRGSR",
        //       "product_price": 8990,
        //       "product_thumbnail": "https://rukminim1.flixcart.com/image/416/416/kgiaykw0/mobile/g/s/r/oppo-a33-cph2137-original-imafwqg8vkpgs265.jpeg?q=70",
        //       "closing_remark": "3GB RAM | 32 GB ROM | 5000 mAh Lithium-ion Polymer Battery",
        //     }
        //   },
        //   {
        //     "id": "db_005",
        //     "title": "speaker",
        //     "custom_title": "70% price drop on sound bar",
        //     "result": {
        //       "id": "bdr_005",
        //       "product_name": "boAt Aavante Bar 2000 160 W Bluetooth Soundbar",
        //       "product_type": "speaker",
        //       "product_brand": "boAt",
        //       "product_link": "https://www.flipkart.com/boat-aavante-bar-2000-160-w-bluetooth-soundbar/p/itmfe5qyjynhdgqg?pid=ACCFE5HS2YP2ZZBE",
        //       "product_price": 7999,
        //       "product_thumbnail": "https://rukminim1.flixcart.com/image/416/416/k6fd47k0pkrrdj/speaker-refurbished/g/b/h/a-aavante-bar-1550-boat-original-imafk9gd9vmcgzxr.jpeg?q=70",
        //       "closing_remark": "Bluetooth Soundbar",
        //     }
        //   }
    ],
    'bestRecc': [
        {
            "id": 110,
            "title": "laptop",
            "custom_title": "Compact and powerful",
            "result": {
                "id": 348,
                "product_name": "LG Gram 14",
                "product_type": "laptop",
                "product_brand": "LG",
                "product_link": "https://amzn.to/3cDjgT2",
                "product_price": 99900,
                "product_thumbnail": "https://m.media-amazon.com/images/I/51eTOVYRbTL._SL252_.jpg",
                "closing_remark": "12th Gen Core i7 | 16 GB Ram | 512 GB SSD | 14inch Screen",
            }
        },
        {
            "id": 109,
            "title": "phone",
            "custom_title": "New Launch by Apple",
            "custom_cta": "Pre order now",
            "result": {
                "id": 347,
                "product_name": "iPhone 13",
                "product_type": "phone",
                "product_brand": "Apple",
                "product_link": "https://amzn.to/39pC2br",
                "product_price": 109900,
                "product_thumbnail": "https://m.media-amazon.com/images/I/71GLMJ7TQiL._SL252_.jpg",
                "closing_remark": "Super Retina XDR display",
            }
        },
        {
            "id": 106,
            "title": "earphone",
            "custom_title": "Did I hear something?",
            "result": {
                "id": 346,
                "product_name": "Samsung Galaxy Buds Pro ",
                "product_type": "earphone",
                "product_brand": "Samsung",
                "product_link": "https://amzn.to/3zqGy7B",
                "product_price": 6999,
                "product_thumbnail": "https://m.media-amazon.com/images/I/51qVl5jDvIL._SL252_.jpg",
                "closing_remark": "99% Noise Cancellation | Bluetooth Truly Wireless | with Mic | Charging 18 Hours Playtime,",
            }
        },
        {
            "id": 103,
            "title": "tv",
            "custom_title": "Powerful TV",
            "result": {
                "id": 345,
                "product_name": "Redmi 126 cm",
                "product_type": "tv",
                "product_brand": "redmi",
                "product_link": "https://amzn.to/3S19xWH",
                "product_price": 28990,
                "product_thumbnail": "https://m.media-amazon.com/images/I/71YDOppqAzL._SL252_.jpg",
                "closing_remark": "50 Inch | 4K Ultra HD ",
            }
        },
        {
            "id": 102,
            "title": "laptop",
            "custom_title": "Best budget laptop",
            "result": {
                "id": 345,
                "product_name": " Lenovo IdeaPad Slim 3 2021",
                "product_type": "laptop",
                "product_brand": "lenovo",
                "product_link": "https://amzn.to/3ByMVUr",
                "product_price": 43990,
                "product_thumbnail": "https://m.media-amazon.com/images/I/61XJ6xrICAL._SL1252_.jpg",
                "closing_remark": "11th Gen i3 | Thin and Light | Fingerprint Reader | 14inch",
            }
        },
        {
            "id": 98,
            "created": "2021-08-16T09:57:08.404Z",
            "updated": "2021-08-16T10:02:12.444Z",
            "title": "earphone",
            "description": null,
            "keywords": "",
            "max_budget": 20000,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 3,
            "customer_id": 1,
            "custom_title": 'On heavy discount',
            "result": {
                "id": 341,
                "created": "2021-08-16T09:57:08.111Z",
                "updated": "2021-08-16T09:57:08.111Z",
                "product_name": "Infinity (JBL) Glide 120",
                "product_type": "earphone",
                "product_brand": "JBL",
                "product_link": "https://amzn.to/38tNrXp",
                "product_price": 1234,
                "product_thumbnail": "https://m.media-amazon.com/images/I/51jJccFRVxS._SL252_.jpg",
                "closing_remark": "Deep Bass | Dual Equilizer | Comfortable Neckband",
                "alternate_result": null,
                "keywords": ""
            }
        },
        {
            "id": 101,
            "created": "2021-08-16T16:14:16.155Z",
            "updated": "2021-08-16T16:24:01.567Z",
            "title": "watch",
            "description": null,
            "keywords": "",
            "max_budget": 30000,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 3,
            "customer_id": 1,
            "custom_title": 'New Launch',
            "result": {
                "id": 344,
                "created": "2021-08-16T16:14:15.840Z",
                "updated": "2021-08-16T16:14:15.840Z",
                "product_name": "Samsung Galaxy Watch4",
                "product_type": "watch",
                "product_brand": "Samsung",
                "product_link": "https://amzn.to/3sZGwyQ",
                "product_price": 16999,
                "product_thumbnail": "https://m.media-amazon.com/images/I/61Nhi7ovjkL._SS252_.jpg",
                "closing_remark": "Lastest from Samsung | Health Monitoring ",
                "alternate_result": null,
                "keywords": ""
            }
        },
        {
            "id": 99,
            "created": "2021-08-16T10:07:31.493Z",
            "updated": "2021-08-16T10:16:41.884Z",
            "title": "laptop",
            "description": null,
            "keywords": "Gaming, High performance",
            "max_budget": 75000,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 3,
            "customer_id": 1,
            "result": {
                "id": 342,
                "created": "2021-08-16T10:07:30.202Z",
                "updated": "2021-08-16T10:07:30.202Z",
                "product_name": "ASUS TUF Dash F15",
                "product_type": "laptop",
                "product_brand": "ASUS",
                "product_link": "https://amzn.to/3sNInXp",
                "product_price": 74990,
                "product_thumbnail": "https://m.media-amazon.com/images/I/81stVUZ+WuL._SS252_.jpg",
                "closing_remark": "FHD Gaming laptop | 11th Gen Intel i5 | 8/512 (ssd) | RTX 3050 4GB Graphics",
                "alternate_result": null,
                "keywords": "FHD Display, Gaming, high performance"
            }
        },
        {
            "id": 138,
            "created": "2021-08-23T07:46:43.966Z",
            "updated": "2021-08-23T08:15:27.108Z",
            "title": "television",
            "description": "",
            "keywords": "Good Sound Quality,4K,Smart TV",
            "max_budget": 55000,
            "min_budget": 45000,
            "status": 3,
            "recommendation_type": 0,
            "agent_id": 2,
            "customer_id": 122,
            "result": {
              "id": 381,
              "created": "2021-08-23T07:46:43.913Z",
              "updated": "2021-08-23T07:46:43.913Z",
              "product_name": "Samsung 55 inch Crystal 4K Series Ultra HD Smart LED",
              "product_type": "television",
              "product_brand": "Samsung",
              "product_link": "https://amzn.to/3DbLGwg",
              "product_price": 53990,
              "product_thumbnail": "https://m.media-amazon.com/images/I/61GwJAhftvS._SL252_.jpg",
              "closing_remark": " 4K Ultra HD (3840x2160) | 20 Watts Output | 20 Watts Output | Powerful Speakers with Dolby Digital Plus",
              "alternate_result": null,
              "keywords": "4k, good sound quality, smart tv, dolby atoms "
            }
        },
        {
            "id": 136,
            "created": "2021-08-22T06:40:59.984Z",
            "updated": "2021-08-22T06:47:08.350Z",
            "title": "router",
            "description": null,
            "keywords": "",
            "max_budget": 1500,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 2,
            "customer_id": 1,
            "result": {
                "id": 379,
                "created": "2021-08-22T06:40:59.534Z",
                "updated": "2021-08-22T06:40:59.534Z",
                "product_name": "TP-Link TL-WA850RE",
                "product_type": "router",
                "product_brand": "TP-Link",
                "product_link": "https://amzn.to/3mogkwy",
                "product_price": 1399,
                "product_thumbnail": "https://m.media-amazon.com/images/I/31N9ADI8c7L._SL252_.jpg",
                "closing_remark": "Superior Extended Range | 300Mbps Wi-Fi | Wireless Booster",
                "alternate_result": null,
                "keywords": ""
            }
        },
        {
            "id": 135,
            "created": "2021-08-22T06:40:59.984Z",
            "updated": "2021-08-22T06:47:08.350Z",
            "title": "laptop",
            "description": null,
            "keywords": "Gaming, Thin and light, Good battery, Full HD, High Performance",
            "max_budget": 60000,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 2,
            "customer_id": 1,
            "result": {
                "id": 378,
                "created": "2021-08-22T06:40:59.534Z",
                "updated": "2021-08-22T06:40:59.534Z",
                "product_name": "Mi Notebook Horizon Edition",
                "product_type": "laptop",
                "product_brand": "MI",
                "product_link": "https://amzn.to/3gmorpr",
                "product_price": 59990,
                "product_thumbnail": "https://m.media-amazon.com/images/I/712rw0zcH8L._SL252_.jpg",
                "closing_remark": "10th Gen Intel Core i7-10510U processor | 4-Inch (1920X 1080 )Full HD Anti-Glare Screen | Nvidia MX350 2GB GDDR5 Graphics ",
                "alternate_result": null,
                "keywords": "high performance, gaming, thin and light, good battery, full hd"
            }
        },
        {
            "id": 92,
            "created": "2021-08-11T13:12:21.487Z",
            "updated": "2021-08-11T13:16:20.295Z",
            "title": "laptop",
            "description": null,
            "keywords": "Gaming, High Performance, SSD",
            "max_budget": 70000,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 2,
            "customer_id": 1,
            "result": {
                "id": 329,
                "created": "2021-08-11T13:12:21.448Z",
                "updated": "2021-08-11T13:12:21.448Z",
                "product_name": "HP Pavilion Gaming",
                "product_type": "laptop",
                "product_brand": "HP",
                "product_link": "https://amzn.to/3AuLK8b",
                "product_price": 63990,
                "product_thumbnail": "https://m.media-amazon.com/images/I/514oxAHWbnS._SL252_.jpg",
                "closing_remark": "10th Gen Intel Core i5-10300H | 8 GB DDR4-2933 SDRAM |  15.6-Inch FHD IPS micro-edge, anti-glare Display | NVIDIA GeForce GTX 1650 (4 GB GDDR6 dedicated)",
                "alternate_result": null,
                "keywords": "Gaming, High Performance, SSD"
            }
        },
        {
            "id": 100,
            "created": "2021-08-16T11:13:12.365Z",
            "updated": "2021-08-16T16:11:53.280Z",
            "title": "earphones",
            "description": null,
            "keywords": "With Mic, Active Noise Cancellation, In Ear, Bluetooth, Volume Control, Neckband",
            "max_budget": 2000,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 3,
            "customer_id": 1,
            "result": {
                "id": 343,
                "created": "2021-08-16T11:13:11.546Z",
                "updated": "2021-08-16T11:13:11.546Z",
                "product_name": "Bullets Wireless Z Bass Edition",
                "product_type": "earphones",
                "product_brand": "OnePlus",
                "product_link": "https://amzn.to/3AIQ4AP",
                "product_price": 1999,
                "product_thumbnail": "https://images-na.ssl-images-amazon.com/images/I/51R4FJdgbMS._SS252_.jpg",
                "closing_remark": "IP55 Water & Sweat Resistant | Magnetic Control | Bluetooth 5.0 | In-Ear Earphone",
                "alternate_result": null,
                "keywords": "With Mic, Active Noise Cancellation, Water Resistant, In Ear, Bluetooth, Volume Control, Neckband"
            }
        },
        {
            "id": 105,
            "created": "2021-08-16T18:05:08.956Z",
            "updated": "2021-08-16T18:49:43.239Z",
            "title": "cycle",
            "description": null,
            "keywords": "daily use, intermideate",
            "max_budget": 20000,
            "min_budget": 0,
            "status": 3,
            "recommendation_type": 1,
            "agent_id": 3,
            "customer_id": 1,
            "result": {
                "id": 348,
                "created": "2021-08-16T18:05:08.213Z",
                "updated": "2021-08-16T18:05:08.213Z",
                "product_name": "Cyclone D-27.5T",
                "product_type": "cycle",
                "product_brand": "Firefox",
                "product_link": "https://amzn.to/3iQKDJR",
                "product_price": 19999,
                "product_thumbnail": "https://images-na.ssl-images-amazon.com/images/I/61cH5IUIXkS._SS252_.jpg",
                "closing_remark": "Front & Rear Disc Brake | Zoom Suspension Fork | Double Wall Rims",
                "alternate_result": null,
                "keywords": "Light Weight, Mountain Bike, Hybrid, Disc Brake, daily use, Large wheel, Steel Body, Exploration,"
            }
        },
    ]
}

export default StaticWish;